// examples/vue-spa-example/src/App.vue
<script setup lang="ts">
import { createExampleFragmentClient } from "@rejot-dev/example-fragment";
import { useFragno } from "@rejot-dev/fragno/vue";
import { ref, computed } from "vue";

const exampleFragmentClient = createExampleFragmentClient();
const { useData } = useFragno(exampleFragmentClient);

const refreshKey = ref(0);
const shouldTriggerError = ref(false);

const {
  loading,
  data,
  error: dataError,
} = useData({
  queryParams: {
    name: computed(() => refreshKey.value.toString()),
    error: computed(() => (shouldTriggerError.value ? "true" : "")),
  },
});
</script>

<template>
  <div style="margin-bottom: 30px">
    <h2>Current Data:</h2>
    <div
      v-if="loading"
      style="padding: 15px; background-color: #f5f5f5; border-radius: 5px; border: 1px solid #ddd"
    >
      Loading…
    </div>
    <div
      v-else-if="dataError"
      style="
        padding: 15px;
        background-color: #f8d7da;
        border-radius: 5px;
        border: 1px solid #f5c6cb;
        color: #721c24;
      "
    >
      Error: {{ dataError.message }} (code: {{ dataError.code }})
    </div>
    <div
      v-else
      style="padding: 15px; background-color: #f5f5f5; border-radius: 5px; border: 1px solid #ddd"
    >
      {{ data || "No data yet" }}
    </div>
    <div style="margin-top: 15px; display: flex; align-items: center; gap: 8px">
      <input
        id="toggle-error"
        type="checkbox"
        v-model="shouldTriggerError"
        style="margin-right: 6px"
      />
      <label for="toggle-error" style="font-size: 14px; color: #333"> Trigger error </label>
    </div>
  </div>
</template>

<style scoped></style>

// examples/nextjs-example/app/page.tsx
"use client";

import { createExampleFragmentClient } from "@rejot-dev/example-fragment";
import { useFragno } from "@rejot-dev/fragno/client/react";

const exampleFragmentClient = createExampleFragmentClient();
const { useData } = useFragno(exampleFragmentClient);

export default function Home() {
  const { data: currentData, loading: dataLoading } = useData();

  return (
    <div style={{ padding: "20px", fontFamily: "monospace", maxWidth: "800px", margin: "0 auto" }}>
      <h1>Next.js Fragno Example Fragment</h1>
      <p>Simple data reading with example-fragment</p>

      <div style={{ marginBottom: "30px" }}>
        <h2>Current Data</h2>
        {dataLoading ? (
          <p>Loading…</p>
        ) : (
          <div
            style={{
              padding: "15px",
              backgroundColor: "#f5f5f5",
              borderRadius: "5px",
              border: "1px solid #ddd",
            }}
          >
            {currentData || "No data yet"}
          </div>
        )}
      </div>

      <div style={{ marginTop: "30px", fontSize: "14px", color: "#666" }}>
        <h3>Available Endpoints:</h3>
        <ul>
          <li>GET /api/example-fragment/ - Hello World</li>
          <li>GET /api/example-fragment/data - Retrieve current data</li>
        </ul>
      </div>
    </div>
  );
}
